<div class="wrap">
    <h2><?php echo $this->plugin->displayName; ?> &raquo; <?php _e('Import &amp; Export', $this->plugin->name); ?></h2>
           
    <?php    
    if (isset($this->message)) {
        ?>
        <div class="updated fade"><p><?php echo $this->message; ?></p></div>  
        <?php
    }
    if (isset($this->errorMessage)) {
        ?>
        <div class="error fade"><p><?php echo $this->errorMessage; ?></p></div>  
        <?php
    }
    ?> 
    
    <div id="poststuff">
    	<div id="post-body" class="metabox-holder columns-1">
    		<!-- Content -->
    		<div id="post-body-content">
				<div id="normal-sortables" class="meta-box-sortables ui-sortable">  
					<!-- Import --> 
					<form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post" enctype="multipart/form-data">
						<?php
						wp_nonce_field($this->plugin->name, $this->plugin->name.'_nonce');
		                ?>
		                
					    <div class="postbox">
						    <h3 class="hndle"><?php _e('Import', $this->plugin->name); ?></h3>
						    
						    <div class="inside">
						    	<p>
						    		<?php _e('Upload a JSON file generated by this plugin to import settings. This will overwrite any existing settings stored on this installation.', $this->plugin->name); ?>
						    	</p>
						    	<p>
						    		<input type="file" name="import" />
						    	</p>
						    	<p>
									<input name="submit" type="submit" name="Submit" class="button button-primary" value="<?php _e('Import', $this->plugin->name); ?>" /> 
								</p>
						    </div>
						</div>
					</form>
					
					<!-- Export -->
					<div class="postbox">
					    <h3 class="hndle"><?php _e('Export', $this->plugin->name); ?></h3>
					    
					    <div class="inside">
					    	<p>
								<?php _e('To export all plugin settings, click the Export button below.', $this->plugin->name); ?><br />
								<?php _e('You can then import the generated JSON file into another plugin installation.', $this->plugin->name); ?>
							</p>
						    <p>
						    	<a href="admin.php?page=<?php echo $this->plugin->name; ?>-import-export&export=1" class="button button-primary">
						    		<?php _e('Export', $this->plugin->name); ?>
						    	</a>
							</p> 
					    </div>
					</div>
				</div>
				<!-- /normal-sortables -->
    		</div>
    		<!-- /post-body-content -->
    	</div>
	</div>      
</div>